name: dart_bootstrap_datepicker
description: Bootstrap Datepicker for Angular Dart developers.
version: 0.0.1
#author: Pongpat Weesommai <empongpat@gmail.com>
#homepage: https://github.com/shinzenkoru/dart_bootstrap_datepicker

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  angular2: 2.0.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: example/main.dart
